---
deployment:
  tasks:
    - export DEPLOYPATH=/home/animenew/public_html/temporadas/
    - rsync -a --exclude='.git*' .output/public/ $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
    - pm2 restart nuxt3-app || pm2 start .output/server/index.mjs --name nuxt3-app
