---
deployment:
  tasks:
    - export NVM_DIR="$HOME/.nvm"
    - source $NVM_DIR/nvm.sh
    - npm install
    - npm run build
    - pm2 stop nuxt-app || true # Stop previous instance if running
    - pm2 start .output/server/index.mjs --name nuxt-app # Start new instance
